version: '3.8'
services:
  gateway:
    build: gateway
    image: gateway
    container_name: gateway-container
    ports:
      - "8080:8888"
    depends_on:
      - server
    environment:
      - SERVER_PORT=8888
      - SHAREIT_SERVER_URL=http://server:9999

  server:
    build: server
    image: server
    container_name: server-container
    ports:
      - "9090:9999"
    depends_on:
      - db
    environment:
      - SERVER_PORT=9999
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=share
      - SPRING_DATASOURCE_PASSWORD=share

  db:
    image: postgres:15.2-alpine
    container_name: share-it-postgres-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=share
      - POSTGRES_PASSWORD=share